apiVersion: v1
kind: BuildConfig
metadata:
  name: recco-dev-pipeline
  labels:
    app: recco-dev-pipeline
    name: recco-dev-pipeline
    template: recco-dev-pipeline
spec:
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
          stage('Build'){
            checkout scm
            sh "mvn fabric8:build"
          }  
          stage('Deploy'){
            sh "mvn fabric8:deploy"
          }  
          stage 'Test'
            sh 'echo "testing"'
          stage 'Promote to QA'
            input 'Proceeed ?'
            sh 'oc tag bi-dev/recommendations:1.0.0 bi-dev/recommendations:promoteToQA'
        }
  output:
  resources:
  postCommit:
