apiVersion: v1
kind: BuildConfig
metadata:
  name: recco-dev-pipeline
  labels:
    app: recco-dev-pipeline
    name: recco-dev-pipeline
    template: recco-dev-pipeline
spec:
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('') {
          stage 'Build'
            openshiftBuild(namespace:'bi-dev',buildConfig: 'reccomendations', showBuildLogs: 'true')
          stage 'Deploy'
            openshiftDeploy(namespace:'bi-dev',deploymentConfig: 'reccomendations')
          stage 'Test'
            sh 'echo "testing"'
          stage 'Promote to QA'
            input 'Proceeed ?'
            sh 'oc tag bi-dev/reccomendations:latest bi-dev/reccomendations:promoteToQA'
        }
  output:
  resources:
  postCommit:
