apiVersion: v1
kind: BuildConfig
metadata:
  name: recommendations-qa-pipeline
  labels:
    app: recommendations-qa-pipeline
    name: recommendations-qa-pipeline
    template: recommendations-qa-pipeline
spec:
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('') {
          stage 'Copy from DEV'
            sh 'oc tag bi-dev/recommendations:promoteToQA bi-qa/recommendations:promoteToQA'
          stage 'Deploy to QA'
            sh 'oc new-app bi-qa/recommendations:promoteToQA --name=recommendations --dry-run -o yaml | oc apply -f-'
          stage 'Test'
            sh 'echo "testing"'
          stage 'Promote to Prod'
            input 'Proceeed ?'
            sh 'oc tag bi-qa/recommendations:promoteToQA bi-qa/recommendations:promoteToProd'
        }
  output:
  resources:
  postCommit:
