apiVersion: v1
kind: BuildConfig
metadata:
  name: recommendations-qa-pipeline
  labels:
    app: recommendations-qa-pipeline
    name: recommendations-qa-pipeline
    template: recommendations-qa-pipeline
spec:
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('') {
          stage 'Copy from DEV'
            sh 'oc tag bi-dev/recommendations:latest bi-qa/recommendations:promoteToQA'
          stage 'Deploy to QA'
            openshiftDeploy(namespace:'bi-qa',deploymentConfig: 'recommendations')
          stage 'Test'
            sh 'echo "testing"'
          stage 'Promote to Prod'
            input 'Proceeed ?'
            sh 'oc tag bi-qa/recommendations:latest bi-qa/recommendations:promoteToQA'
        }
  output:
  resources:
  postCommit:
